### PR TITLE
Move params from puppet::config to puppet topdir class

### PR DESCRIPTION
**Pull request by tampakrap**
This way we won't have to include puppet::config at all, and we won't have
to use both puppet and puppet::config in our hieradata, but only the former

### CODE REVIEW

**Comment by igalic** [comment]
:+1: good good

**Comment by igalic** [comment]
@xaque208 ping

**Comment by xaque208** [comment]
+1 That seems reasonable.

**Comment by tampakrap** [comment]
I reverted the last commit (that combined the ini_settings) https://github.com/puppetlabs-operations/puppet-puppet/pull/189/files#r24914032

**Comment by igalic** [comment]
i'll merge and see what this does to us…
i definitely agree that it's a step in the right direction

**Pull request merged**
