### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by igalic** [comment]
how about extracting this reference and putting it all into README?

**Comment by tampakrap** [comment]
You mean to put all the params docs in README?

**Comment by tampakrap** [comment]
Oh and btw I have some questionmarks there, I'd like some suggestions for them

**Comment by igalic** [comment]
yes, i think we should extract the reference documentation and put it all into the README.

It's better formated, can be properly linked, and it's all in one place.

re ??s:

[parser](https://docs.puppetlabs.com/references/3.7.latest/configuration.html#parser): which parser puppet will use internally. can be `current`, or `future`. Default: `current`.

**Comment by tampakrap** [comment]
sure, I'll do that as well

**Comment by igalic** [comment]
kthanx

**Comment by xaque208** [comment]
+1

**Pull request merged**
