### PR TITLE
improve the rack code in passenger and unicorn

### PR DESCRIPTION
**Pull request by tampakrap**
- include puppet::server::rack in both of them
- create the same config.ru
- move the resources that create the rack files in puppet::server::rack

extra:
- fix the variables in the unicorn class to be from puppet or from
  puppet::server classes instead of puppet::params, in order to respec the user
  submitted changes
- ability to pass IP on the nginx vhost
- when using unicorn+nginx, we need to restart unicorn and not nginx
- remove obsolete templates
- bump puppet and rspec versions in Gemfile

### CODE REVIEW

**Comment by tampakrap** [comment]
I dropped ruby1.9 because of these failures https://travis-ci.org/puppetlabs-operations/puppet-puppet/builds/148650600

**Comment by danieldreier** [comment]
This looks fine to me, but I don't actually use this module anymore. I'm glad to see some maintenance happening.

**Comment by igalic** [comment]
i have switched to puppet apply only…

**Comment by tampakrap** [comment]
@danieldreier mind approving this and releasing it as 1.0.1 please?

**Comment by danieldreier** [comment]
@tampakrap I've released this to Forge as 1.0.1, and made PR https://github.com/puppetlabs-operations/puppet-puppet/pull/231 to bump the version.

**Pull request merged**
