### PR TITLE
Create the agent config even if $puppet::agent::ensure is a version or latest

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by danieldreier** [comment]
+1; the errors in travis-ci are not related to this change:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/lib/metadata-json-lint/semantic/version_range.rb:30:in `parse': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/lib/metadata_json_lint.rb:76:in `block in parse'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/lib/metadata_json_lint.rb:75:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/lib/metadata_json_lint.rb:75:in `parse'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/lib/metadata_json_lint.rb:37:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-0.0.5/bin/metadata-json-lint:8:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/metadata-json-lint:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/metadata-json-lint:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
```

**Comment by igalic** [comment]
our metadata.json is bad, see https://github.com/puppetlabs-operations/puppet-puppet/issues/164

**Comment by danieldreier** [comment]
I re-ran the travis tests now that the metadata.json fixes were applied, so tests pass. I believe that this is good to merge.

**Comment by igalic** [comment]
i believe you are right!

**Pull request merged**
