### PR TITLE
Added the noop variable configuration for the agent

### PR DESCRIPTION
**Pull request by mvisonneau**
I needed this feature and thought it might interest some other people.

### CODE REVIEW

**Comment by igalic** [comment]
so, i hit merge, and then immediately realized: this makes no sense:

when i enable noop, and then want to disable it again, what happens?

nothing.

**Comment by danieldreier** [comment]
@igalic that's actually pretty funny. I hadn't thought of that either.

**Comment by mvisonneau** [comment]
hehe yes indeed, my plan is actually to use `mcollective` in order to remove the option if I need too.

**Comment by igalic** [comment]
```puppet
$noop_ensure = $puppet::agent::noop? {
  undef   => 'absent',
  default => 'present',
}
ini_setting { 'noop':
  ensure  => $noop_ensure,
  setting => 'noop',
  value   => $puppet::agent::noop,
}
```

**Pull request merged**
