### PR TITLE
Updates for OSX

### PR DESCRIPTION
**Pull request by xaque208**
Some minor updates to OSX agent management.

### CODE REVIEW

**Comment by igalic** [comment]
not feeling entirely comfortable to make this call
the general look and feel of this change checks out, but i don't know how that affects actual users.

**Comment by xaque208** [comment]
Nor I, but given that its still referencing `puppetd`, its probably been a while since anyone was using that code.

**Comment by igalic** [comment]
yank?

**Comment by xaque208** [comment]
This probably needs better testing.

**Comment by danieldreier** [comment]
I think this is fine to merge; I'm not real confident that we have any users of it anyway; given that it was referencing `puppetd` the worst case here is that we turned broken code into differently broken code.

**Comment by xaque208** [comment]
It can be easily backed out of someone complains.  I just want to configure some exported resources from a personal laptop. :)

**Comment by danieldreier** [comment]
I don't see a reason to reject reasonable improvements because we don't have test coverage, when we're not incrementally losing test coverage. I'm going to merge this; if that really bothers anybody please let me know and I'll be more conservative about merging in the future on this project.

**Pull request merged**
