### PR TITLE
Add support for tagmail.conf

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by igalic** [comment]
new parameter with no docs :p

**Comment by tampakrap** [comment]
On purpose, because there isn't any params doc for this class yet

**Comment by igalic** [comment]
btw, tagmail doesn't set reports += tagmail, is that also on purpose?

**Comment by tampakrap** [comment]
Nope, I'll fix it

**Comment by tampakrap** [comment]
Actually, how to fix it? Print a failure when there is no tagmail in puppet::server::reports?

**Comment by igalic** [comment]
*i have* ***no*** *idea*

**Comment by xaque208** [comment]
Is this feature actually something folks want to use, or just that Puppet supports it, so the module should to?

**Comment by igalic** [comment]
***I*** don't use it.

i'm guessing @tampakrap does?

**Comment by tampakrap** [comment]
yes I need it for my company, right now I have the same code in my profile module and I thought it is a good idea to have it here, as it will have minimal to zero effort to maintain it.

**Comment by tampakrap** [comment]
So I gave a thought regarding the reports = tagmail issue and I think it's better to leave it as it is. We can only warn/fail if we use `puppet::server::tagmail` but don't have tagmail in `puppet::server::reports`, or if we set tagmail `puppet::server::reports` but don't use `puppet::server::tagmail`. For the second case, there's still the possibility the user might set tagmail in reports, but would like to install his own static file instead

**Comment by igalic** [comment]
:+1:

**Comment by xaque208** [comment]
+1

**Comment by tampakrap** [comment]
I'm merging this then, and I'll add the docstrings for it in my documentation PR, thanks for the review

**Pull request merged**
